version: "3.9"

services:
  blocks:
    image: adamrehn/ue4-runtime:18.04-cudagl10.2
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ${PWD}/Binaries:/home/ue4/Binaries
      - ${PWD}/settings_headless.json:/home/ue4/Documents/AirSim/settings.json
    command: bash /home/ue4/Binaries/Blocks/LinuxNoEditor/Blocks.sh -RenderOffScreen
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
